### ISSUE TITLE
"Nested" workers cause parent to quit when join returns 

### ISSUE THREAD

**Issue by wise0wl** [chadrem/workers#4]
I have code that creates a worker pool, which then calls code that then in turn (in an included library) creates a new worker pool to execute concurrent shell commands, and then waits on them.  However my nested worker pool causes the "parent" to quit when join returns.

**Comment by chadrem** [comment]
@wise0wl Can you provide a small example demonstrating the problem?

**Comment by chadrem** [comment]
@wise0wl Have you had a chance to look into this?  If you figured it out then please let me know so I can close the issue.

**Comment by wise0wl** [comment]
OK, let me come up with a sanitized sample ( cant use work code :) )

**Comment by wise0wl** [comment]
```ruby
require 'workers'

class DoStuff

  def initialize
    @worker_pool = Workers::Pool.new
  end

  def do_work
    (1..5).each do |num|
      @worker_pool.perform do
        `sleep #{num} ; echo done > #{num}.out`
      end
      @worker_pool.join
    end
  end

end

workers = Workers::Pool.new

workers.perform do
  begin
    stuff = DoStuff.new
    stuff.do_work
  rescue Exception => e
    puts "Exception: #{e.message}"
  end
end

# wait for workers
begin
  workers.join
rescue Exception => e
  puts "Workers joined: #{e.message}"
end
```

**Comment by chadrem** [comment]
Thanks!  I'm going take a look at it soon and then I'll get back to you.  

  -Chad

**Comment by chadrem** [comment]
@wise0wl I believe I know what is going on.  Are you getting the below error?
"No live threads left. Deadlock? (fatal)"

I just want to make sure I am debugging the exact problem you are experiencing.  I'll go into more detail once I know for sure.

**Comment by wise0wl** [comment]
Yes, that is the error I get.  Basically, once a single nested worker completes, I get the "No live threads left" exception and the whole thing quits.

**Comment by chadrem** [comment]
@wise0wl Your code was calling join() without first calling shutdown().  This results in Ruby detecting deadlock because there is no way for your code to ever finish.

I realize this is confusing and my goal is to make Workers as easy to use as possible.  I have refactored the API and now you only need to call dispose().  Behind the scenes it will take care of calling shutdown() and join() for you.  I also recommend you pass it a timeout and I have updated all the examples to show this.  I've updated your example to demonstrate the changes and I hope you find it easier to use.  Please update to the new gem and let me know if you run into problems.  I really want to get this right so everyone can avoid these low level threading problems.  Your feedback is welcome!

````ruby
class DoStuff

  def initialize
    @worker_pool = Workers::Pool.new(:on_exception => proc { |e|
      puts "Inner Worker exception: #{e.message}"
    })
  end

  def do_work
    (1..5).each do |num|
      @worker_pool.perform do
        raise "sad face: #{num}" if rand < 0.5
        `sleep #{num} ; echo done > #{num}.out`
      end
    end
    @worker_pool.dispose(30)
  end

end

workers = Workers::Pool.new(:on_exception => proc { |e|
  puts "Outer Worker exception: #{e.message}"
})

workers.perform do
  stuff = DoStuff.new
  stuff.do_work
end

workers.dispose(30)
````

**Comment by chadrem** [comment]
Feel free to re-open the issue if you are still encountering the problem.
